# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSOt4RtOCUdcsxGRdtpUfg5qBAuOZ8Uh
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Load clustered data
df = pd.read_csv("clustered_jobs.csv")

st.title("JobLens: Semantic Job Role Clustering")

# Cluster selector
clusters = sorted(df['cluster'].unique())
selected_cluster = st.selectbox("Choose a Cluster", clusters)

# Filter jobs in selected cluster
cluster_df = df[df['cluster'] == selected_cluster]

st.subheader(f"Sample Job Titles in Cluster {selected_cluster}")
st.write(cluster_df['title'].value_counts().head(10))

# Show top skills in the cluster
all_words = ','.join(cluster_df['keywords']).split(',')
top_skills = pd.Series([w.strip() for w in all_words]).value_counts().head(10)

st.subheader("Top Skills in This Cluster")
for skill in top_skills.index:
    st.markdown(f"- {skill}")

# Plot (optional)
st.subheader("Cluster Position in UMAP Space")
fig = px.scatter(df, x='x', y='y', color='cluster',
                 hover_data=['title', 'keywords'],
                 title="UMAP Projection of Job Role Clusters",
                 width=900, height=600)
st.plotly_chart(fig)